### ISSUE TITLE
C++ Aws::String =  Aws::String crash

### ISSUE THREAD

**Issue by yuandaxing** [aws/aws-sdk-cpp#1303]
### What platform/OS are you using?
docker (Ubuntu 5.4.0-6ubuntu1~16.04.11)
### Which version of the SDK?
   newest
### What compiler are you using? what version?
 gcc version 5.4.0 20160609 
### What are your CMake arguments?
cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_ONLY="s3" ../
### Can you provide a TRACE level log? (sanitize any sensitive information)
cfg_.endpointOverride = addr; //crash at this line 
#0  0x00000000008e4acf in __gnu_cxx::__exchange_and_add (__val=-1, __mem=0x3e0) at /usr/include/c++/5/ext/atomicity.h:49
#1  __gnu_cxx::__exchange_and_add_dispatch (__val=-1, __mem=0x3e0) at /usr/include/c++/5/ext/atomicity.h:82
#2  std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >::_Rep::_M_dispose (this=0x3d0, __a=...)
    at /usr/include/c++/5/bits/basic_string.h:2642
#3  0x00000000008efa3c in std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >::_Rep::_M_dispose (
    __a=<synthetic pointer>, this=<optimized out>) at /usr/include/c++/5/ext/atomicity.h:53
#4  std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >::assign (__str="xxx", this=0x7f8b0e9d2730)
    at /usr/include/c++/5/bits/basic_string.tcc:694
#5  std::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >::operator= (__str="xxx", this=0x7f8b0e9d2730)
    at /usr/include/c++/5/bits/basic_string.h:2951
#6  S3Operator::S3Operator (bucket_name="xxx", secret_key="xxx", 
    access_key="xxx", server_addr="xxx", this=0x7f8b0e9d26b0)
    at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/common/aws_s3_op.h:31
#7  ps::server::CheckpointUtils::WriteToS3 (this=this@entry=0x7f8b0e9d2c20)
    at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc:850
#8  0x00000000008f1049 in ps::server::CheckpointUtils::SaveVariables (this=this@entry=0x7f8b0e9d2c20, id=<optimized out>, vars=...)
    at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc:281
#9  0x00000000009169d7 in ps::server::Server::Save (this=0x7f8b1142a4c0, ver=<optimized out>, 
    checkpoint="/data/yuandaxing1/online-learning/ckpt/st_pnn_xdl_ol_cookie_label/2020-01-07/ckpt", info=..., 
    inference="/data/yuandaxing1/online-learning/load-model/load-setting/xdl_ckpt_setting.json")
    at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/server/server.cc:79
#10 0x000000000091ad59 in ps::server::ServerService::Save (this=0x7fff74b59bb0, inputs=std::vector of length 4, capacity 4 = {...}, 
    outputs=0x7f8a80080128) at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/server/server_service.cc:220
#11 0x000000000091af34 in ps::server::ServerService::<lambda(const std::vector<ps::Data*, std::allocator<ps::Data*> >&, std::vector<ps::Data*, std::allocator<ps::Data*> >*, ps::service::seastar::DoneClosure*)>::<lambda()>::operator() (__closure=0x7f8a800fdd90)
    at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/server/server_service.cc:96
#12 std::_Function_handler<void(), ps::server::ServerService::Init()::<lambda(const std::vector<ps::Data*>&, std::vector<ps::Data*>*, ps::service::seastar::DoneClosure*)>::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5/functional:1871
#13 0x0000000000893975 in std::function<void ()>::operator()() const (this=0x7f8b0e9d2e30) at /usr/include/c++/5/functional:2267
#14 ps::ThreadPool::Loop (this=0x7f8b114b63a0) at /data/yuandaxing1/x-deeplearning/xdl/ps-plus/ps-plus/common/thread_pool.cc:38
#15 0x00007f8b1986ec80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007f8b17b866ba in start_thread (arg=0x7f8b0e9dc700) at pthread_create.c:333
#17 0x00007f8b175b341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by yuandaxing** [comment]
I have see other similiar problems, but could not help

**Comment by yuandaxing** [comment]
I find the problem, i should use -D_GLIBCXX_USE_CXX11_ABI=0 param
