### ISSUE TITLE
Segment fault on GetObject

### ISSUE THREAD

**Issue by lzw06061139** [aws/aws-sdk-cpp#1378]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

we run our backup app on docker on CentOS Linux release 7.6.1810 (Core).
This app uses (AWS SDK for C++ with Version:1.7.314) to put  to or get data from object storage system. 

**Describe the question**

GetObject gets random segment fault. it seems caused by memory allocator. 

**Logs/output**
If applicable, add logs or error output.

0  0x00007f6ee4768af2 in _int_malloc () from /usr/lib64/libc.so.6
#1  0x00007f6ee476badc in malloc () from /usr/lib64/libc.so.6
#2  0x00007f6ee6fca529 in void std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<
char> >, Aws::Allocator<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > > >::_M_rea
lloc_insert<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> > >(__gnu_cxx::__normal_i
terator<std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >*, std::vector<std::__cxx11:
:basic_string<char, std::char_traits<char>, Aws::Allocator<char> >, Aws::Allocator<std::__cxx11::basic_string<char,
 std::char_traits<char>, Aws::Allocator<char> > > > >, std::__cxx11::basic_string<char, std::char_traits<char>, Aws
::Allocator<char> >&&) () from /usr/lib64/libaws-cpp-sdk-s3.so
#3  0x00007f6ee69f2f85 in Aws::Utils::StringUtils::Split(std::__cxx11::basic_string<char, std::char_traits<char>, A
ws::Allocator<char> > const&, char, unsigned long, Aws::Utils::StringUtils::SplitOptions) () from /usr/lib64/libaws
-cpp-sdk-core.so
#4  0x00007f6ee69f32d6 in Aws::Utils::StringUtils::Split(std::__cxx11::basic_string<char, std::char_traits<char>, A
ws::Allocator<char> > const&, char, Aws::Utils::StringUtils::SplitOptions) () from /usr/lib64/libaws-cpp-sdk-core.s
o
#5  0x00007f6ee69e7ade in Aws::Utils::ARN::ARN(std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Alloca
tor<char> > const&) () from /usr/lib64/libaws-cpp-sdk-core.so
#6  0x00007f6ee6f2b1e9 in Aws::S3::S3ARN::S3ARN(std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Alloc
ator<char> > const&) () from /usr/lib64/libaws-cpp-sdk-s3.so
#7  0x00007f6ee6f459c5 in Aws::S3::S3Client::ComputeEndpointString(std::__cxx11::basic_string<char, std::char_trait
s<char>, Aws::Allocator<char> > const&) const () from /usr/lib64/libaws-cpp-sdk-s3.so
#8  0x00007f6ee6f5892b in Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const () from /usr/
lib64/libaws-cpp-sdk-s3.so

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by lzw06061139** [comment]
after upper segment fault triggered， no coredump , the backup app is still running, but it's stucked on GetObject.

**Comment by lzw06061139** [comment]
this is the pstack piece :
#0  0x00007f27e3b7757c in __lll_lock_wait_private () from /usr/lib64/libc.so.6
#1  0x00007f27e3af3af5 in _L_lock_17166 () from /usr/lib64/libc.so.6
#2  0x00007f27e3af0b33 in malloc () from /usr/lib64/libc.so.6
#3  0x00007f27e43e2498 in operator new (sz=513) at ../../../../libstdc++-v3/libsupc++/new_op.cc:50
#4  0x00007f27e924589a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve (this=this@entry=0x7f27d9885aa0, __res=<optimized out>) at /opt/gnu/gcc-7.5.0/include/c++/7.5.0/bits/basic_string.tcc:293
#5  0x00007f27e446592b in std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow (this=0x7f27d9885bf8, __c=111) at /root/work/gcc-7.5.0/build/x86_64-redhat-linux/libstdc++-v3/include/bits/sstream.tcc:133
#6  0x00007f27e44706a9 in std::basic_streambuf<char, std::char_traits<char> >::xsputn (this=0x7f27d9885bf8, __s=0x7f27e7adb417 "on ", __n=18) at /root/work/gcc-7.5.0/build/x86_64-redhat-linux/libstdc++-v3/include/bits/streambuf.tcc:98
#7  0x00007f27e4460a44 in sputn (__n=18, __s=0x7f27e7adb408 "protector version ", this=<optimized out>) at /root/work/gcc-7.5.0/build/x86_64-redhat-linux/libstdc++-v3/include/streambuf:451
#8  __ostream_write<char, std::char_traits<char> > (__n=18, __s=0x7f27e7adb408 "protector version ", __out=...) at /root/work/gcc-7.5.0/build/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream_insert.h:50
#9  std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=__s@entry=0x7f27e7adb408 "protector version ", __n=__n@entry=18) at /root/work/gcc-7.5.0/build/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream_insert.h:101
#10 0x00007f27e7aca3e8 in operator<< <std::char_traits<char> > (__s=<optimized out>, __out=...) at /opt/gnu/gcc-7.5.0/include/c++/7.5.0/ostream:561
#11 pretty_version_to_str[abi:cxx11]() () at /root/chinac/ar-protector-core/src/common/version.cc:24
#12 0x00007f27e7a9944a in protector::BackTrace::print (this=0x7f27d9886020, out=...) at /root/chinac/ar-protector-core/src/common/BackTrace.cc:15
#13 0x00000000004112cb in handle_fatal_signal (signum=11) at /root/chinac/ar-protector-core/src/global/signal_handler.cc:88
#14 <signal handler called>
#15 0x00007f27e3aec2bf in _int_free () from /usr/lib64/libc.so.6
#16 0x00007f27e264772a in curl_multi_wait () from /usr/lib64/libcurl.so.4
#17 0x00007f27e26407cf in curl_easy_perform () from /usr/lib64/libcurl.so.4
#18 0x00007f27e5d515c8 in Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::shared_ptr<Aws::Http::Standard::StandardHttpResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const () from /usr/lib64/libaws-cpp-sdk-core.so
#19 0x00007f27e5d53ed9 in Aws::Http::CurlHttpClient::MakeRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const () from /usr/lib64/libaws-cpp-sdk-core.so
#20 0x00007f27e5d20c74 in Aws::Client::AWSClient::AttemptOneRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&, char const*, char const*) const () from /usr/lib64/libaws-cpp-sdk-core.so
#21 0x00007f27e5d211ff in Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*) const () from /usr/lib64/libaws-cpp-sdk-core.so
#22 0x00007f27e5d22f3e in Aws::Client::AWSClient::MakeRequestWithUnparsedResponse(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*) const () from /usr/lib64/libaws-cpp-sdk-core.so
#23 0x00007f27e62dda38 in Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const () from /usr/lib64/libaws-cpp-sdk-s3.so
#24 0x00007f27e884bcde in S3_Client::get_object (this=this@entry=0x11fb580, bucket=..., name=..., data=data@entry=0x7f27d98895c0) at /root/chinac/ar-protector-core/src/storage/s3client.cc:42
