### ISSUE TITLE
TransferManager::RetryUpload(...) causes TransferHandle::WaitUntilCompleted() to hang indefinitely when transferred bytes > total bytes

### ISSUE THREAD

**Issue by devyndraen** [aws/aws-sdk-cpp#1571]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
When transferring data from an in-memory buffer to S3 using the TransferManager, transfer failures were sometimes seen (which is reasonable and almost expected due to the nature of uploads/downloads).  When they occurred, our code's retry logic invoked TransferManager::RetryUpload.  When we use the returned handle object to call WaitUntilFinished, the method hung indefinitely.

```
Thread 3 (Thread 0x2acef7f6d700 (LWP 23961)):
#0  0x00002aceecbd1a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib64/libpthread.so.0
#1  0x00002aceee398aec in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib64/libstdc++.so.6
#2  0x00002acee60da50a in Aws::Transfer::TransferHandle::WaitUntilFinished (this=0x2ad107004198) at <FOSS-repo>/aws-sdk-cpp-1.8.25/aws-cpp-sdk-transfer/source/transfer/TransferHandle.cpp:340
... (redacted calling code)
```

Forcing a core with gcore and examining the memory showed the following contents of the TransferHandle:

```
$1 = {m_isMultipart = {<std::atomic_bool> = {_M_base = {_M_i = true}}, <No data fields>},
  m_multipartId = "REDACTED MULTIPART ID", m_direction = Aws::Transfer::UPLOAD, m_completedParts = std::map with 22 elements = {
    [1] = std::shared_ptr (count 1, weak 0) 0x2acfe8002318, [2] = std::shared_ptr (count 1, weak 0) 0x2acfe8097e28, [3] = std::shared_ptr (count 1, weak 0) 0x2acfe8097ac8, [4] = std::shared_ptr (count 1, weak 0) 0x2acfe8000d28,
    [5] = std::shared_ptr (count 1, weak 0) 0x2acfe8000d98, [6] = std::shared_ptr (count 1, weak 0) 0x2acfe8097ec8, [7] = std::shared_ptr (count 1, weak 0) 0x2acfe8097f38, [8] = std::shared_ptr (count 1, weak 0) 0x2acfe8000e98,
    [9] = std::shared_ptr (count 1, weak 0) 0x2acfe8000f08, [10] = std::shared_ptr (count 1, weak 0) 0x2acfe80978e8, [11] = std::shared_ptr (count 1, weak 0) 0x2acfe8097958, [12] = std::shared_ptr (count 1, weak 0) 0x2acfe8097148,
    [13] = std::shared_ptr (count 1, weak 0) 0x2acfe80971b8, [14] = std::shared_ptr (count 1, weak 0) 0x2acfe8001a28, [15] = std::shared_ptr (count 1, weak 0) 0x2acfe8001a98, [16] = std::shared_ptr (count 1, weak 0) 0x2acfe8001b08,
    [17] = std::shared_ptr (count 1, weak 0) 0x2acfe8001878, [18] = std::shared_ptr (count 1, weak 0) 0x2acfe80018e8, [19] = std::shared_ptr (count 1, weak 0) 0x2acfe8001958, [20] = std::shared_ptr (count 1, weak 0) 0x2acfe8002018,
    [21] = std::shared_ptr (count 1, weak 0) 0x2acfe8002088, [22] = std::shared_ptr (count 1, weak 0) 0x2acfe80020f8}, m_pendingParts = std::map with 0 elements, m_queuedParts = std::map with 0 elements,
  m_failedParts = std::map with 0 elements, m_bytesTransferred = {<std::__atomic_base<unsigned long>> = {_M_i = 111137335}, <No data fields>}, m_lastPart = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>},
  m_bytesTotalSize = {<std::__atomic_base<unsigned long>> = {_M_i = 110989879}, <No data fields>}, m_offset = 0, m_bucket = "REDACTED BUCKET", m_key = "REDACTED KEY",
  m_fileName = "", m_contentType = "binary/octet-stream", m_versionId = "", m_metadata = std::map with 2 elements = {["ETag"] = "\"REDACTED ETAG\"",
    ["sha384-hash"] = "REDACTED HASH"}, m_status = Aws::Transfer::IN_PROGRESS, m_lastError = {m_errorType = 1279697684, m_exceptionName = "", m_message = "",
    m_remoteHostIpAddress = "", m_requestId = "", m_responseHeaders = std::map with 0 elements, m_responseCode = Aws::Http::REQUEST_NOT_MADE, m_isRetryable = false, m_errorPayloadType = (unknown: 21530208), m_xmlPayload = {m_doc =
    0x0}, m_jsonPayload = {m_value = 0x0, m_wasParseSuccessful = true, m_errorMessage = ""}}, m_cancel = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>}, m_context = std::shared_ptr (empty) 0x0, m_handleId = {
    m_uuid = "REDACTED UUID"}, m_createDownloadStreamFn = {<std::_Maybe_unary_or_binary_function<std::basic_iostream<char, std::char_traits<char> >*>> = {<No data fields>}, <std::_Function_base> = {
      static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x2acf200a9860, _M_const_object = 0x2acf200a9860, _M_function_pointer = 0x2acf200a9860,
          _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x2acf200a9860, this adjustment 7146983061701555304}, _M_pod_data = "`\230\n ?*\000\000http://c"}, _M_manager = 0x0},
    _M_invoker = 0x2acedd9a72ac <std::_Function_handler<std::iostream* (), MY_CLASS::MY_METHOD(char const*, void*, unsigned long, char const*)::{lambda()#1}>::_M_invoke(std::_Any_data const&)>},
  m_downloadStream = 0x0, m_downloadStreamLock = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
        __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, m_partsLock = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0,
          __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, m_statusLock = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 1,
          __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 12 times>, "\001", '\000' <repeats 26 times>, __align = 0}}, <No data fields>}, m_waitUntilFinishedSignal = {_M_cond = {
      __data = {__lock = 0, __futex = 3, __total_seq = 2, __wakeup_seq = 1, __woken_seq = 1, __mutex = 0x2ad107004418, __nwaiters = 2, __broadcast_seq = 1},
      __size = "\000\000\000\000\003\000\000\000\002\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\030D\000\a?*\000\000\002\000\000\000\001\000\000", __align = 12884901888}},
  m_getterSetterLock = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
        __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}}
```

Note that the m_bytesTransferred of 111137335 is larger than the m_bytesTotalSize of 110989879.

Further examination of the PartStates in the completed parts map showed:
```
(gdb) print (Aws::Transfer::PartState)*0x2acfe8002318
$2 = {m_partId = 1, m_eTag = "\"1442c59f2ff1962d280da5c87b9bec6e\"", m_currentProgressInBytes = 5242880, m_bestProgressInBytes = 5242880, m_sizeInBytes = 5242880, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = false}
(gdb) print (Aws::Transfer::PartState)*0x2acfe8097e28
$3 = {m_partId = 2, m_eTag = "\"eafba4cde6a0266da029e23bb2eb0d9d\"", m_currentProgressInBytes = 5242880, m_bestProgressInBytes = 5242880, m_sizeInBytes = 5242880, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = false}
(gdb) print (Aws::Transfer::PartState)*0x2acfe80020f8
$4 = {m_partId = 22, m_eTag = "\"b75e21897c87ec2a08a0f664622127e3\"", m_currentProgressInBytes = 889399, m_bestProgressInBytes = 889399, m_sizeInBytes = 889399, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = true}
(gdb) print (Aws::Transfer::PartState)*0x2acfe8097ac8
$5 = {m_partId = 3, m_eTag = "\"83576a3de70b4d10bbc2b54a1bd6dc52\"", m_currentProgressInBytes = 5242880, m_bestProgressInBytes = 5242880, m_sizeInBytes = 5242880, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = false}
(gdb) print (Aws::Transfer::PartState)*0x2acfe8000d28
$6 = {m_partId = 4, m_eTag = "\"f4bc83e735d6e4dc81e3b85db2542e17\"", m_currentProgressInBytes = 5242880, m_bestProgressInBytes = 5242880, m_sizeInBytes = 5242880, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = false}
(gdb) print (Aws::Transfer::PartState)*0x2acfe8000d98
$7 = {m_partId = 5, m_eTag = "\"74a180656bcbaa60859d8703f7de20b4\"", m_currentProgressInBytes = 5292032, m_bestProgressInBytes = **5292032**, m_sizeInBytes = 5242880, m_rangeBegin = 0, m_downloadPartStream = {_M_b = {_M_p = 0x0}},
  m_downloadBuffer = {_M_b = {_M_p = 0x0}}, m_lastPart = false}
```

The part examined as $7 above shows a current and best progress value of 5292032 which is larger than the size in bytes of 5242880.  Upon detailed examination of the code in TransferManager::HandleUploadPartResponse (line 538 in version 1.8.25), I found:

```
            if (pendingParts.size() == 0 && queuedParts.size() == 0 && handle->LockForCompletion())
            {
                if (failedParts.size() == 0 && handle->GetBytesTransferred() == handle->GetBytesTotalSize())
                {
                    *attempt to convert state to COMPLETED*
```

Since the bytes transferred and the bytes total size are not equal (in fact the amount transferred is _more_), then the upload never transitions to a COMPLETED state and any WaitUntilFinished calls will never return.

I suspect that the culprit here is that somewhere along the retry path, the PartState is not getting reset (via the handy Reset method) which causes the m_currentProgressInBytes variable to retain the original progress that was made in the initial upload attempt.

**SDK version number**
aws-sdk-cpp-1.8.25 (aws-c-common-0.4.51, aws-checksums-0.1.6, aws-c-event-stream-0.1.8).  Note that while this is an older version, I did look at changes to the TransferManager and TransferHandle classes since that release and did not note anything that would seem to solve this issue.

**Platform/OS/Hardware/Device**
AWS EC2, various instance sizes
Red Hat Enterprise Linux Server release 7.9 (Maipo)
RHEL 3.10.0-1160.11.1.el7.x86_64

**To Reproduce (observed behavior)**
Since this only occurs on failure to upload a file to S3, which happens very infrequently and there is little in the way of exposed APIs available to simulate this condition, I am not able to provide a SSCCE that demonstrates this.  I can, however, provide a synopsis of our implementation.  The localBufferPtr variable is the in-memery buffer (as a void*) that we are attempting to upload.

```
      // Create the AWS-style buffer for it to upload the data from
      Aws::Utils::Stream::PreallocatedStreamBuf* writeBuffer =
         Aws::New<Aws::Utils::Stream::PreallocatedStreamBuf>
            ("writeBuffer", reinterpret_cast<unsigned char*>(localBufferPtr), length);

      std::shared_ptr<Aws::IOStream> writeStream = Aws::MakeShared<Aws::IOStream>(
         "writeStream", writeBuffer);

      auto handle = myTransferManager->UploadFile(
         writeStream, storageRoot, simplePath.c_str(), "binary/octet-stream", metadata);

      handle->WaitUntilFinished();
      ***at this point, the transfer fails***

      *** our max retries is 5, although every process that has hung never makes it past the first retry attempt ***
      for( int i=0; !retVal->wasTransferSuccessful()
                 && i < myMaxTransferRetries; i++ )
      {
         *** sleep 500 milliseconds ***
         handle = myTransferManager->RetryUpload(writeStream, handle);

         handle->WaitUntilFinished();
         *** The process hangs on the above call indefinitely (caller of the stack trace at the top of this bug report) ***
      }

```

The TransferManager was configured with:
max thread pool = 50
multi part buffer size = <SDK default, which I believe is currently 5MB>
total buffer size = 262144000

The S3Client was configured with (due to issue https://github.com/aws/aws-sdk-cpp/issues/271):
connect timeout = 60ms
request timeout = 60ms

**Expected behavior**
I expected that the TransferManager would either:
a) correctly track the number of bytes transferred by accounting for the fact that some bytes may have been transferred in previous attempts
or
b) allow the transfer to be marked as completed if all parts are completed, no parts are failed/pending/queued, and the number of bytes transferred equals or exceeds the number of bytes requested to be transferred by the user of the TransferManager API.

Preferably option a) would be the ultimate behavior exhibited since that is a much more accurate manner of accounting in this situation.

**Logs/output**
All relevant output was provided in the description above (no logging was turned on during these occurrences)

**Additional context**
The system experiencing this issue is a data processing system that uploads millions of files of varying sizes (a few KB to 100s of MB) to S3 every day, but this issue was only found in 4 processes out of hundreds over the course of several days to a week of processing.  Thus, reproducing the issue in a similar manner would likely take either some intense resources, or direct access to lower level API calls that would result in this behavior.  Ideally, some additional unit testing surrounding the retry logic in the TransferManager/TransferHandler can be constructed to reproduce this issue.

**Comment by KaibaLopez** [comment]
Hi @devyndraen ,
Thanks for bringing this up to us and sorry for the delayed response.
Yea this seems like an overlooked edge case, I'll try and investigate see if I can figure a way to reliably reproduce it.
