### ISSUE TITLE
AudioStream::WriteAudioEvent() freezes at transcribestreaming 

### ISSUE THREAD

**Issue by yzabalotski** [aws/aws-sdk-cpp#1586]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
AudioStream::WriteAudioEvent() freezes at transcribestreaming. I wrote an integration test to illustrate the issue. See below. It mostly occurs during some error handling like throttling. 

**SDK version number**
Latest master, commit sha(757b9c41a801a4048bb99c2656b6cabafc27e455)
**Platform/OS/Hardware/Device**
Fedora release 33
**To Reproduce (observed behavior)**
```
1) setup creds via env vars
2) run ./aws-cpp-sdk-transcribestreaming-integration-tests --gtest_filter=TranscribeStreamingTests.TranscribeAudioFileConcurrent
```
Code of the test:
```
diff --git a/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp b/aws-cpp-sdk-transcribestreaming-integration-test
s/TranscribeTests.cpp
index ea250f3577..6df20939f4 100644
--- a/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp
+++ b/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp
@@ -267,4 +267,108 @@ TEST_F(TranscribeStreamingTests, TranscribeStreamingWithRequestRetry)
     semaphore.WaitOne();
 }
 
+TEST_F(TranscribeStreamingTests, TranscribeAudioFileConcurrent)
+{
+    Aws::Vector<unsigned char> content;
+    {
+        Aws::FStream file(TEST_FILE_NAME, std::ios_base::in | std::ios_base::binary);
+        ASSERT_TRUE(file);
+        char buf[1024];
+        while(file)
+        {
+            file.read(buf, sizeof(buf));
+            Aws::Vector<unsigned char> bits{buf, buf + file.gcount()};
+            content.insert(content.end(), bits.begin(), bits.end());
+        }
+    }
+
+    std::vector<std::thread> workers;
+    for (int i = 0; i < 30; i++) {
+    workers.push_back(std::thread([this, content]() {
+
+    Aws::String transcribedResult;
+    StartStreamTranscriptionHandler handler;
+    handler.SetTranscriptEventCallback([&transcribedResult](const TranscriptEvent& ev)
+    {
+        // TODO: only check the result marked as "final"
+        const auto& results = ev.GetTranscript().GetResults();
+        if (results.empty())
+        {
+            return;
+        }
+        const auto& last = results.back();
+        const auto& alternatives = last.GetAlternatives();
+        if (alternatives.empty())
+        {
+            return;
+        }
+        transcribedResult = alternatives.back().GetTranscript();
+    });
+
+    handler.SetOnErrorCallback([&transcribedResult](const Aws::Client::AWSError<TranscribeStreamingServiceErrors>& e)
+    {
+        std::cerr << e << std::endl;
+        // we will receive an error because the request was abruptly shutdown (via stream.Close()).
+        // However, we cannot delay the call to closing the stream, because HTTP clients such as libcurl buffer the
+        // requests before sending them over the wire, so it will keep BUFFER_SIZE bytes in its memory if we don't
+        // signal the completion of the stream (by closing it).
+        // To discern between that case and a true error, we check if we have received any text back from the service.
+
+        /* would like to see if WriteAudioEvent() will return
+        if(transcribedResult.empty())
+        {
+            FAIL();
+        }
+        */
+    });
+
+    StartStreamTranscriptionRequest request;
+    request.SetMediaSampleRateHertz(8000);
+    request.SetLanguageCode(LanguageCode::en_US);
+    request.SetMediaEncoding(MediaEncoding::pcm);
+    request.SetEventStreamHandler(handler);
+
+    auto OnStreamReady = [&content](AudioStream& stream)
+    {
+        for (size_t pos = 0; pos < content.size(); pos += 1024)
+        {
+            Aws::Vector<unsigned char> bits{content.begin() + pos, content.begin() + std::min(pos + 1024, content.size())};
+            AudioEvent event(std::move(bits));
+            if (!stream)
+            {
+                break;
+            }
+            if (!stream.WriteAudioEvent(event))
+            {
+                break;
+            }
+        }
+        stream.WriteAudioEvent({}); // per the spec, we have to send an empty event (i.e. without a payload) at the end.
+        stream.flush();
+        stream.Close();
+    };
+
+    Aws::Utils::Threading::Semaphore semaphore(0, 1);
+    auto OnResponseCallback = [&semaphore](const TranscribeStreamingServiceClient*,
+            const StartStreamTranscriptionRequest&,
+            const StartStreamTranscriptionOutcome&,
+            const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)
+    {
+        semaphore.ReleaseAll();
+    };
+
+    Aws::Client::ClientConfiguration config;
+    auto client = Aws::MakeUnique<TranscribeStreamingServiceClient>(ALLOC_TAG, config);
+    client->StartStreamTranscriptionAsync(request, OnStreamReady, OnResponseCallback, nullptr/*context*/);
+    semaphore.WaitOne();
+
+    }));
+    }
+
+    for (auto& worker : workers)
+    {
+        worker.join();
+    }
+}
+
 #endif
```
Hangs at:
```
#0  0x00007fd6dd55a6c2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fd6dd433980 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x00007fd6dd87a82e in std::condition_variable::wait<Aws::Utils::Stream::ConcurrentStreamBuf::FlushPutArea()::<lambda()> >(std::unique_lock<std::mutex> &, struct {...}) (this=0x7fd6481baeb8, __lock=..., __p=...) at /usr/include/c++/10/condition_variable:111
#3  0x00007fd6dd877465 in Aws::Utils::Stream::ConcurrentStreamBuf::FlushPutArea (this=0x7fd6481bae08) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/ConcurrentStreamBuf.cpp:45
#4  0x00007fd6dd8778c6 in Aws::Utils::Stream::ConcurrentStreamBuf::overflow (this=0x7fd6481bae08, ch=0) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/stream/ConcurrentStreamBuf.cpp:106
#5  0x00007fd6dd4a2d9a in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /lib64/libstdc++.so.6
#6  0x00007fd6dd495287 in std::ostream::write(char const*, long) () from /lib64/libstdc++.so.6
#7  0x00007fd6dd83e0ee in Aws::Utils::Event::EventEncoderStream::WriteEvent (this=0x7fd6481badf0, msg=...) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-core/source/utils/event/EventEncoderStream.cpp:23
#8  0x00000000004347aa in Aws::TranscribeStreamingService::Model::AudioStream::WriteAudioEvent (this=0x7fd6481badf0, value=...) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming/include/aws/transcribestreaming/model/AudioStream.h:35
#9  0x000000000042e130 in operator() (__closure=0x7fd6577fdc20, stream=...) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp:341
#10 0x000000000043268b in std::__invoke_impl<void, TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()>::<lambda(Aws::TranscribeStreamingService::Model::AudioStream&)>&, Aws::TranscribeStreamingService::Model::AudioStream&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#11 0x0000000000431636 in std::__invoke_r<void, TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()>::<lambda(Aws::TranscribeStreamingService::Model::AudioStream&)>&, Aws::TranscribeStreamingService::Model::AudioStream&>(struct {...} &) (__fn=...) at /usr/include/c++/10/bits/invoke.h:153
#12 0x000000000042ff32 in std::_Function_handler<void(Aws::TranscribeStreamingService::Model::AudioStream&), TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()>::<lambda(Aws::TranscribeStreamingService::Model::AudioStream&)> >::_M_invoke(const std::_Any_data &, Aws::TranscribeStreamingService::Model::AudioStream &) (__functor=..., __args#0=...) at /usr/include/c++/10/bits/std_function.h:291
#13 0x00007fd6dda9b667 in std::function<void (Aws::TranscribeStreamingService::Model::AudioStream&)>::operator()(Aws::TranscribeStreamingService::Model::AudioStream&) const (this=0x7fd6577fdc20, __args#0=...) at /usr/include/c++/10/bits/std_function.h:622
#14 0x00007fd6dda89494 in Aws::TranscribeStreamingService::TranscribeStreamingServiceClient::StartStreamTranscriptionAsync(Aws::TranscribeStreamingService::Model::StartStreamTranscriptionRequest&, std::function<void (Aws::TranscribeStreamingService::Model::AudioStream&)> const&, std::function<void (Aws::TranscribeStreamingService::TranscribeStreamingServiceClient const*, Aws::TranscribeStreamingService::Model::StartStreamTranscriptionRequest const&, Aws::Utils::Outcome<Aws::NoResult, Aws::TranscribeStreamingService::TranscribeStreamingServiceError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (this=0x7fd648003310, request=..., streamReadyHandler=..., responseHandler=..., handlerContext=std::shared_ptr<const Aws::Client::AsyncCallerContext> (empty) = {...}) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming/source/TranscribeStreamingServiceClient.cpp:216
#15 0x000000000042e446 in operator() (__closure=0x11040b8) at /home/yahor/projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming-integration-tests/TranscribeTests.cpp:362
#16 0x0000000000432f48 in std::__invoke_impl<void, TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#17 0x0000000000432efd in std::__invoke<TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/10/bits/invoke.h:95
#18 0x0000000000432eaa in std::thread::_Invoker<std::tuple<TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x11040b8) at /usr/include/c++/10/thread:264
#19 0x0000000000432e7e in std::thread::_Invoker<std::tuple<TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()> > >::operator()(void) (this=0x11040b8) at /usr/include/c++/10/thread:271
#20 0x0000000000432e62 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<TranscribeStreamingTests_TranscribeAudioFileConcurrent_Test::TestBody()::<lambda()> > > >::_M_run(void) (this=0x11040b0) at /usr/include/c++/10/thread:215
#21 0x00007fd6dd4395f4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#22 0x00007fd6dd5543f9 in start_thread () from /lib64/libpthread.so.0
#23 0x00007fd6dd136b53 in clone () from /lib64/libc.so.6

```

**Expected behavior**
The test shouldn't freeze.

**Additional context**
Similar issue https://github.com/aws/aws-sdk-cpp/issues/1236.

**Comment by jmklix** [comment]
There are internal code changes pending approval that should fix this. I will update here when those changes are merged.

**Comment by yzabalotski** [comment]
@jmklix 
Any news?

**Comment by jmklix** [comment]
No updates, but I am doing what I can to make sure it gets reviewed promptly and properly.

**Comment by jmklix** [comment]
The fix has been merged and is now live.

**Comment by yzabalotski** [comment]
@jmklix
Should I use latest AWS CPP SDK version?

**Comment by jmklix** [comment]
@yzabalotski yes
