### ISSUE TITLE
build fail on AL2 with segfault in test AWSAuthV4ASignerTest.GetHeaderValueMultiline

### ISSUE THREAD

**Issue by ozbenh** [aws/aws-sdk-cpp#1791]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
Building the SDK on my AL2 (dev desktop) system fails with the following error during tests:

```
[----------] 19 tests from AWSAuthV4ASignerTest
[ RUN      ] AWSAuthV4ASignerTest.GetHeaderValueMultiline
/bin/sh: line 1: 87157 Segmentation fault      ./aws-cpp-sdk-core-tests --gtest_shuffle --gtest_repeat=3
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 139
make[2]: *** Deleting file `aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make: *** [all] Error 2

```
**SDK version number**
1.9.118

**Platform/OS/Hardware/Device**
What are you running the sdk on?
AL2 x86_64 (c3.8xlarge)

**To Reproduce (observed behavior)**
* Clone the git repo
* mkdir build
* cd build
* cmake3 .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/home/benh/aws-sdk-cpp
* make

**Expected behavior**
The SDK should build

**Logs/output**
As above. I can provide more complete log or log files upon request (or benh@amazon.com)

I can also perform more debugging with a little help sorting out the build system

**Comment by ozbenh** [comment]
I managed to kill -9 make so it doesn't delete the test program and got this backtrace when running in gdb:

`Thread 1 "aws-cpp-sdk-cor" received signal SIGSEGV, Segmentation fault.
0x00007ffff6cf08b5 in EVP_MD_CTX_clear_flags () from /lib64/libcrypto.so.1.1
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.amzn2.x86_64 keyutils-libs-1.5.8-3.amzn2.0.2.x86_64 krb5-libs-1.15.1-37.amzn2.2.2.x86_64 libcom_err-1.42.9-19.amzn2.x86_64 libcrypt-2.26-54.amzn2.x86_64 libcurl-7.76.1-7.amzn2.0.2.x86_64 libgcc-7.3.1-13.amzn2.x86_64 libidn2-2.3.0-1.amzn2.x86_64 libnghttp2-1.41.0-1.amzn2.x86_64 libselinux-2.5-12.amzn2.0.2.x86_64 libssh2-1.4.3-12.amzn2.2.3.x86_64 libstdc++-7.3.1-13.amzn2.x86_64 libunistring-0.9.3-9.amzn2.0.2.x86_64 nspr-4.25.0-2.amzn2.x86_64 nss-3.53.1-7.amzn2.x86_64 nss-util-3.53.1-1.amzn2.x86_64 openldap-2.4.44-23.amzn2.0.2.x86_64 openssl-libs-1.0.2k-19.amzn2.0.7.x86_64 openssl11-libs-1.1.1g-12.amzn2.0.3.x86_64 pcre-8.32-17.amzn2.0.2.x86_64 zlib-1.2.7-18.amzn2.x86_64
(gdb) backtrace 
#0  0x00007ffff6cf08b5 in EVP_MD_CTX_clear_flags () from /lib64/libcrypto.so.1.1
#1  0x00007ffff6cdf2cd in EVP_DigestInit_ex () from /lib64/libcrypto.so.1.1
#2  0x00007ffff6cfecad in HMAC_Init_ex () from /lib64/libcrypto.so.1.1
#3  0x00007ffff7781baa in aws_sha256_hmac_default_new (allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, secret=0x7fffffffb5c0)
    at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-cal/source/unix/opensslcrypto_hmac.c:76
#4  0x00007ffff777ed58 in aws_sha256_hmac_new (allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, secret=0x7fffffffb5c0)
    at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-cal/source/hmac.c:23
#5  0x00007ffff777ef8b in aws_sha256_hmac_compute (allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, secret=0x7fffffffb5c0, 
    to_hmac=0x7fffffffb5b0, output=0x7fffffffb610, truncate_to=0)
    at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-cal/source/hmac.c:69
#6  0x00007ffff766b5a1 in aws_ecc_key_pair_new_ecdsa_p256_key_from_aws_credentials (
    allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, credentials=0xfa2400)
    at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-auth/source/key_derivation.c:350
#7  0x00007ffff765fe53 in aws_credentials_new_ecc_from_aws_credentials (allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, 
    credentials=0xfa2400) at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-auth/source/credentials.c:254
#8  0x00007ffff766c093 in aws_sign_request_aws (allocator=0x7ffff7b159e0 <Aws::get_aws_allocator()::wrapper>, signable=0xd7c3e0, 
    base_config=0x7fffffffba00, on_complete=0x7ffff76406d9 <Aws::Crt::Auth::s_http_signing_complete_fn(aws_signing_result*, int, void*)>, 
    userdata=0xeeaef0) at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-auth/source/signing.c:147
#9  0x00007ffff7640959 in Aws::Crt::Auth::Sigv4HttpRequestSigner::SignRequest(std::shared_ptr<Aws::Crt::Http::HttpRequest> const&, Aws::Crt::Auth::ISigningConfig const&, std::function<void (std::shared_ptr<Aws::Crt::Http::HttpRequest> const&, int)> const&) (this=0xee70a0, request=
    std::shared_ptr (count 2, weak 0) 0xfd7750, config=..., completionCallback=...)
    at /home/benh/work/aws-sdk-cpp/crt/aws-crt-cpp/source/auth/Sigv4Signing.cpp:258
#10 0x00007ffff75d965d in Aws::Client::AWSAuthV4Signer::SignRequestWithSigV4a (this=0x7fffffffd2d0, request=..., 
    region=0x7fffffffc760 "us-east-1", serviceName=0x7fffffffd308 "service", signBody=false, expirationTimeInSeconds=0, 
    signatureType=Aws::Crt::Auth::SignatureType::HttpRequestViaHeaders)
    at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core/source/auth/AWSAuthSigner.cpp:245
#11 0x00007ffff75d99f4 in Aws::Client::AWSAuthV4Signer::SignRequest (this=0x7fffffffd2d0, request=..., region=0x7fffffffd328 "us-east-1", 
    serviceName=0x7fffffffd308 "service", signBody=false) at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core/source/auth/AWSAuthSigner.cpp:318
#12 0x00000000006267ca in Aws::Client::AWSAuthV4Signer::SignRequest (this=0x7fffffffd2d0, request=..., signBody=true)
    at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/auth/AWSAuthSigner.h:245
#13 0x0000000000621fb8 in RunTestCaseWithPayload (testCaseName=0x7bf41d "post-x-www-form-urlencoded", 
    policy=Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, scheme=Aws::Http::Scheme::HTTP, requestSignPayload=true)
    at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core-tests/aws/auth/AWSAuthSignerTest.cpp:407
#14 0x000000000062378f in AWSAuthSignerTest_PayloadSigningPolicyNever_Test::TestBody (this=0xeeac60)
    at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core-tests/aws/auth/AWSAuthSignerTest.cpp:478
#15 0x00007ffff7ba99ba in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0xeeac60, 
    method=&virtual testing::Test::TestBody(), location=0x7ffff7bb8303 "the test body")
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:3844
#16 0x00007ffff7ba4b73 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0xeeac60, 
    method=&virtual testing::Test::TestBody(), location=0x7ffff7bb8303 "the test body")
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:3897
#17 0x00007ffff7b8d984 in testing::Test::Run (this=0xeeac60)
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:3916
#18 0x00007ffff7b8e0be in testing::TestInfo::Run (this=0xa8d230)
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:4094
#19 0x00007ffff7b8e677 in testing::TestCase::Run (this=0xa8d100)
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:4212
#20 0x00007ffff7b94195 in testing::internal::UnitTestImpl::RunAllTests (this=0xa8c4a0)
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:6082
#21 0x00007ffff7baa833 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xa8c4a0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x7ffff7b93e9a <testing::internal::UnitTestImpl::RunAllTests()>, location=0x7ffff7bb8b30 "auxiliary test code (environments or event listeners)")
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:3844
#22 0x00007ffff7ba5501 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xa8c4a0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x7ffff7b93e9a <testing::internal::UnitTestImpl::RunAllTests()>, location=0x7ffff7bb8b30 "auxiliary test code (environments or event listeners)")
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:3897
#23 0x00007ffff7b930c8 in testing::UnitTest::Run (this=0x7ffff7dd8a60 <testing::UnitTest::GetInstance()::instance>)
    at /home/benh/work/aws-sdk-cpp/testing-resources/source/external/gtest-all.cc:5694
#24 0x000000000061b1f2 in RUN_ALL_TESTS () at /home/benh/work/aws-sdk-cpp/testing-resources/include/aws/external/gtest.h:21259
#25 0x000000000061b13f in main (argc=2, argv=0x7fffffffe388) at /home/benh/work/aws-sdk-cpp/aws-cpp-sdk-core-tests/RunTests.cpp:37
`
It dies in OpenSSL 1.1 (which is optional as the distro default in AL2 is 1.0.2). Now that's interesting as during the build I see this warning:

```
/usr/bin/ld: warning: libcrypto.so.10, needed by //usr/lib64/libcurl.so.4, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.10, needed by //usr/lib64/libcurl.so.4, may conflict with libcrypto.so.1.1
```

**Comment by ozbenh** [comment]
It appears to have disappeared after a full rebuild ... closing.
