### ISSUE TITLE
SNS PublishAsync Memory Leak

### ISSUE THREAD

**Issue by ayeganov** [aws/aws-sdk-cpp#1909]
### Describe the bug

When I publish a message using SNSClient using `PublishAsync` method it causes a memory leak.

### Expected Behavior

No memory leaks

### Current Behavior

This is the stack trace from libasan showing libcrypto leaking memory.

```
==569960==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x7f58b4b6dc47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f58b46a5c0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x556e3c4f8729 in s2n_drbg_instantiate (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad8b729)
    #3 0x556e3c4f2fcc in s2n_get_private_random_data (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad85fcc)
    #4 0x556e3c4f3020 in s2n_openssl_compat_rand (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad86020)
    #5 0x556e3c31854b in Aws::Utils::Crypto::SecureRandomBytes_OpenSSLImpl::GetBytes(unsigned char*, unsigned long) (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabab54b)
    #6 0x556e3c371314 in Aws::Utils::UUID::RandomUUID() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xac04314)
    #7 0x556e3c334ff5 in Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabc7ff5)
    #8 0x556e3c343e4f in Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd6e4f)
    #9 0x556e3c2a9368 in Aws::SNS::SNSClient::Publish(Aws::SNS::Model::PublishRequest const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab3c368)
    #10 0x556e3c28fb18 in Aws::SNS::SNSClient::PublishAsyncHelper(Aws::SNS::Model::PublishRequest const&, std::function<void (Aws::SNS::SNSClient const*, Aws::SNS::Model::PublishRequest const&, Aws::Utils::Outcome<Aws::SNS::Model::PublishResult, Aws::SNS::SNSError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab22b18)
    #11 0x556e3c3429ca in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&)::{lambda()#1}> > >::_M_run() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd59ca)
    #12 0x7f58b496f6b3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda6b3)
    #13 0x7f58b4509608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
    #14 0x7f58b3928162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x7f58b4b6dc47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f58b46a5c0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x556e3c4f8729 in s2n_drbg_instantiate (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad8b729)
    #3 0x556e3c4f2fb2 in s2n_get_private_random_data (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad85fb2)
    #4 0x556e3c4f3020 in s2n_openssl_compat_rand (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad86020)
    #5 0x556e3c31854b in Aws::Utils::Crypto::SecureRandomBytes_OpenSSLImpl::GetBytes(unsigned char*, unsigned long) (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabab54b)
    #6 0x556e3c371314 in Aws::Utils::UUID::RandomUUID() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xac04314)
    #7 0x556e3c334ff5 in Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabc7ff5)
    #8 0x556e3c343e4f in Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd6e4f)
    #9 0x556e3c2a9368 in Aws::SNS::SNSClient::Publish(Aws::SNS::Model::PublishRequest const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab3c368)
    #10 0x556e3c28fb18 in Aws::SNS::SNSClient::PublishAsyncHelper(Aws::SNS::Model::PublishRequest const&, std::function<void (Aws::SNS::SNSClient const*, Aws::SNS::Model::PublishRequest const&, Aws::Utils::Outcome<Aws::SNS::Model::PublishResult, Aws::SNS::SNSError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab22b18)
    #11 0x556e3c3429ca in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&)::{lambda()#1}> > >::_M_run() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd59ca)
    #12 0x7f58b496f6b3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda6b3)
    #13 0x7f58b4509608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
    #14 0x7f58b3928162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

Indirect leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x7f58b4b6dc47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f58b46a5c0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x7f58b4697314 in EVP_CipherInit_ex (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x16d314)
    #3 0x556e3c4f8967 in s2n_drbg_instantiate (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad8b967)
    #4 0x556e3c4f2fcc in s2n_get_private_random_data (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad85fcc)
    #5 0x556e3c4f3020 in s2n_openssl_compat_rand (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad86020)
    #6 0x556e3c31854b in Aws::Utils::Crypto::SecureRandomBytes_OpenSSLImpl::GetBytes(unsigned char*, unsigned long) (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabab54b)
    #7 0x556e3c371314 in Aws::Utils::UUID::RandomUUID() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xac04314)
    #8 0x556e3c334ff5 in Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabc7ff5)
    #9 0x556e3c343e4f in Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd6e4f)
    #10 0x556e3c2a9368 in Aws::SNS::SNSClient::Publish(Aws::SNS::Model::PublishRequest const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab3c368)
    #11 0x556e3c28fb18 in Aws::SNS::SNSClient::PublishAsyncHelper(Aws::SNS::Model::PublishRequest const&, std::function<void (Aws::SNS::SNSClient const*, Aws::SNS::Model::PublishRequest const&, Aws::Utils::Outcome<Aws::SNS::Model::PublishResult, Aws::SNS::SNSError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab22b18)
    #12 0x556e3c3429ca in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&)::{lambda()#1}> > >::_M_run() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd59ca)
    #13 0x7f58b496f6b3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda6b3)
    #14 0x7f58b4509608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
    #15 0x7f58b3928162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

Indirect leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x7f58b4b6dc47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f58b46a5c0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x7f58b4697314 in EVP_CipherInit_ex (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x16d314)
    #3 0x556e3c4f8967 in s2n_drbg_instantiate (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad8b967)
    #4 0x556e3c4f2fb2 in s2n_get_private_random_data (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad85fb2)
    #5 0x556e3c4f3020 in s2n_openssl_compat_rand (/home/ainindza/builds/gateway/gateway/bin/gateway+0xad86020)
    #6 0x556e3c31854b in Aws::Utils::Crypto::SecureRandomBytes_OpenSSLImpl::GetBytes(unsigned char*, unsigned long) (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabab54b)
    #7 0x556e3c371314 in Aws::Utils::UUID::RandomUUID() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xac04314)
    #8 0x556e3c334ff5 in Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabc7ff5)
    #9 0x556e3c343e4f in Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd6e4f)
    #10 0x556e3c2a9368 in Aws::SNS::SNSClient::Publish(Aws::SNS::Model::PublishRequest const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab3c368)
    #11 0x556e3c28fb18 in Aws::SNS::SNSClient::PublishAsyncHelper(Aws::SNS::Model::PublishRequest const&, std::function<void (Aws::SNS::SNSClient const*, Aws::SNS::Model::PublishRequest const&, Aws::Utils::Outcome<Aws::SNS::Model::PublishResult, Aws::SNS::SNSError> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (/home/ainindza/builds/gateway/gateway/bin/gateway+0xab22b18)
    #12 0x556e3c3429ca in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void ()>&&)::{lambda()#1}> > >::_M_run() (/home/ainindza/builds/gateway/gateway/bin/gateway+0xabd59ca)
    #13 0x7f58b496f6b3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda6b3)
    #14 0x7f58b4509608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
    #15 0x7f58b3928162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

SUMMARY: AddressSanitizer: 864 byte(s) leaked in 4 allocation(s).
```

### Reproduction Steps

Build the client below with LibAsan:

```
class AwsSns : public SimpleBus
{
private:
  Aws::SNS::SNSClient client_{};

public:
  void publish_message(std::string, std::string, PubCallback handler) override;
};


void AwsSns::publish_message(std::string msg_body, std::string arn, PubCallback callback)
{
  using namespace Aws::SNS;
  Model::PublishRequest pub_req{};
  pub_req.WithMessage(msg_body).WithTopicArn(arn);

  PublishResponseReceivedHandler h = [cb=std::move(callback)](const auto*, auto&, const Model::PublishOutcome& outcome, const auto&){
    cb(outcome);
  };

  client_.PublishAsync(pub_req, std::move(h));
}
```

### AWS CPP SDK version used

aws-sdk-cpp/1.9.100

### Compiler and Version used

gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

### Operating System and version

Linux Ubuntu 20.04.3 LTS

**Comment by jmklix** [comment]
We fixed a memory with openssl [here](https://github.com/aws/aws-sdk-cpp/pull/2373). Can you update to the latest version of the sdk and see if you are still seeing a memory leak?
