### ISSUE TITLE
Race condition in destructor of EnumParseOverflowContainer

### ISSUE THREAD

**Issue by fukanchik** [aws/aws-sdk-cpp#1919]
### Describe the bug

Our app hangs in a call to AWS API with the following stack trace:
```#0  0x00007fc88fd4054d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fc88fd3d90e in _L_lock_39 () from /lib64/libpthread.so.0
#2  0x00007fc88fd3d848 in pthread_cond_destroy@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#3  0x000000000079ae1d in ~Semaphore (this=0x203ad10, __in_chrg=<optimized out>)
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/include/aws/core/utils/threading/Semaphore.h:18
#4  ~ReaderWriterLock (this=0x203ad00, __in_chrg=<optimized out>)
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/include/aws/core/utils/threading/ReaderWriterLock.h:25
#5  ~EnumParseOverflowContainer (this=0x203ad00, __in_chrg=<optimized out>)
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/include/aws/core/utils/EnumParseOverflowContainer.h:22
#6  Delete<Aws::Utils::EnumParseOverflowContainer> (pointerToT=0x203ad00)
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h:101
#7  Aws::CleanupEnumOverflowContainer ()
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/source/Globals.cpp:26
#8  0x000000000079ac78 in Aws::ShutdownAPI (options=...)
    at PATH/aws-sdk-cpp-1.8.14/src/aws-cpp-sdk-core/source/Aws.cpp:114
#9  <Rest is our code>
```
Is this a known bug? Is there a way to work around it?

### Expected Behavior

Not hanging

### Current Behavior

hanging

### Reproduction Steps

No  easy way to reproduce. Only happens in a specific environment. I _suspect_ it happens when firewall prevents the library to open connection to aws servers.

### AWS CPP SDK version used

1.8.14

### Compiler and Version used

gcc (GCC) 7.3.0

### Operating System and version

CentOS Linux release 7.9.2009 (Core)

**Comment by vudh1** [comment]
Hi @fukanchik thanks for reaching out. Is it still persisting with the current version of SDK? And can you provide the sample of reproducible code that we can use to investigate this better?
