### ISSUE TITLE
[aws-cpp-sdk-core] segmentation faults in MonitoringManager.cpp during Aws::ShutdownAPI

### ISSUE THREAD

**Issue by grrtrr** [aws/aws-sdk-cpp#2135]
### Bug description

We are experiencing segmentation faults at program exit, when `Aws::ShutdownAPI()` invokes `Aws::Monitoring::CleanupMonitoring()`. These segmentation faults render (long-running) batch jobs as failed - despite of running successfully to completion.

Depending on timing, the problems manifest in one of 2 places:
- as `SIGABRT` due to a failed assertion (line 57), or 
- as `SIGSEGV`, due to de-referencing a `nullptr` (line 60).

Here is an example backtrace of the _failed assertion_:
```console
Thread 866 "repro" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff8d636700 (LWP 18321)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ab87f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6aa83fa in __assert_fail_base (fmt=0x7ffff6c2f6c0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555571bb1c1 "s_monitors",
    file=file@entry=0x5555571bb168 "external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp", line=line@entry=57,
    function=function@entry=0x5555571bb440 <Aws::Monitoring::OnRequestFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Aws::Http::HttpRequest const> const&, Aws::Utils::Outcome<std::shared_ptr<Aws::Http::HttpResponse>, Aws::Client::AWSError<Aws::Client::CoreErrors> > const&, Aws::Monitoring::CoreMetricsCollection const&, std::vector<void*, std::allocator<void*> > const&)::__PRETTY_FUNCTION__> "void Aws::Monitoring::OnRequestFailed(const String&, const String&, const std::shared_ptr<const Aws::Http::HttpRequest>&, const HttpResponseOutcome&, const Aws::Monitoring::CoreMetricsCollection&, Aws"...) at assert.c:92
#3  0x00007ffff6aa8472 in __GI___assert_fail (assertion=0x5555571bb1c1 "s_monitors", file=0x5555571bb168 "external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp",
    line=57,
    function=0x5555571bb440 <Aws::Monitoring::OnRequestFailed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Aws::Http::HttpRequest const> const&, Aws::Utils::Outcome<std::shared_ptr<Aws::Http::HttpResponse>, Aws::Client::AWSError<Aws::Client::CoreErrors> > const&, Aws::Monitoring::CoreMetricsCollection const&, std::vector<void*, std::allocator<void*> > const&)::__PRETTY_FUNCTION__> "void Aws::Monitoring::OnRequestFailed(const String&, const String&, const std::shared_ptr<const Aws::Http::HttpRequest>&, const HttpResponseOutcome&, const Aws::Monitoring::CoreMetricsCollection&, Aws"...) at assert.c:101
#4  0x00005555560a5f03 in Aws::Monitoring::OnRequestFailed (serviceName="S3", requestName="GetObject", request=std::shared_ptr<const Aws::Http::HttpRequest> (use count 2, weak count 0) = {...},
    outcome=..., metricsFromCore=..., contexts=std::vector of length 0, capacity 0) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp:57
#5  0x000055555604c94c in Aws::Client::AWSClient::AttemptExhaustively (this=0x7ffff6726090, uri=..., request=..., method=Aws::Http::HttpMethod::HTTP_GET, signerName=0x7fff8d632d20 "SignatureV4",
    signerRegionOverride=0x7fff8d632ce0 "us-east-1", signerServiceNameOverride=0x7fff8d632d00 "s3") at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:276
#6  0x000055555604fe3e in Aws::Client::AWSClient::MakeRequestWithUnparsedResponse (this=0x7ffff6726090, uri=..., request=..., method=Aws::Http::HttpMethod::HTTP_GET,
    signerName=0x7fff8d632d20 "SignatureV4", signerRegionOverride=0x7fff8d632ce0 "us-east-1", signerServiceNameOverride=0x7fff8d632d00 "s3")
    at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:549
#7  0x0000555555ae9ec4 in Aws::S3::S3Client::GetObject (this=0x7ffff6726090, request=...) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1852
#8  0x0000555555aea528 in Aws::S3::S3Client::GetObjectAsyncHelper(Aws::S3::Model::GetObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::GetObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::GetObjectResult, Aws::S3::S3Error>, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const
    (this=0x7ffff6726090, request=..., handler=..., context=std::shared_ptr<const Aws::Client::AsyncCallerContext> (use count 1, weak count 0) = {...})
    at external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1870
#9  0x0000555555aea34e in Aws::S3::S3Client::<lambda()>::operator()(void) const (__closure=0x7ffff150e000) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1865
#10 0x0000555555b7bcb3 in std::__invoke_impl<void, Aws::S3::S3Client::GetObjectAsync(const Aws::S3::Model::GetObjectRequest&, const GetObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>&>(std::__invoke_other, Aws::S3::S3Client::<lambda()> &) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#11 0x0000555555b763f6 in std::__invoke<Aws::S3::S3Client::GetObjectAsync(const Aws::S3::Model::GetObjectRequest&, const GetObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>&>(Aws::S3::S3Client::<lambda()> &) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#12 0x0000555555b6a7e0 in std::_Bind<Aws::S3::S3Client::GetObjectAsync(const Aws::S3::Model::GetObjectRequest&, const GetObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()>::__call<void>(std::tuple<> &&, std::_Index_tuple<>) (this=0x7ffff150e000, __args=...) at /usr/include/c++/7/functional:467
#13 0x0000555555b54c1f in std::_Bind<Aws::S3::S3Client::GetObjectAsync(const Aws::S3::Model::GetObjectRequest&, const GetObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()>::operator()<>(void) (this=0x7ffff150e000) at /usr/include/c++/7/functional:551
#14 0x0000555555b3adc9 in std::_Function_handler<void(), std::_Bind<Aws::S3::S3Client::GetObjectAsync(const Aws::S3::Model::GetObjectRequest&, const GetObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#15 0x0000555555d4c22a in std::function<void ()>::operator()() const (this=0x7ffff140ed28) at /usr/include/c++/7/bits/std_function.h:706
#16 0x00005555560f5b00 in Aws::Utils::Threading::DefaultExecutor::<lambda()>::operator()(void) const (__closure=0x7ffff140ed28)
    at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/threading/Executor.cpp:18
#17 0x00005555560f678d in std::__invoke_impl<void, Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> >(std::__invoke_other, Aws::Utils::Threading::DefaultExecutor::<lambda()> &&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#18 0x00005555560f6508 in std::__invoke<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> >(Aws::Utils::Threading::DefaultExecutor::<lambda()> &&) (__fn=...)
    at /usr/include/c++/7/bits/invoke.h:95
```

Problematic in the above is that `GetObjectAsync` was _still running_ in a thread on program exit.

The `SIGSEGV` trace is similar:
```console
Thread 771 "repro" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbc81a700 (LWP 17759)]
Aws::Monitoring::OnRequestFailed (serviceName="S3", requestName="GetObject", request=std::shared_ptr<const Aws::Http::HttpRequest> (use count 2, weak count 0) = {...}, outcome=..., metricsFromCore=...,
    contexts=std::vector of length 0, capacity 0) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp:60
60                  for (const auto& interface: *s_monitors)
(gdb) bt
#0  Aws::Monitoring::OnRequestFailed (serviceName="S3", requestName="GetObject", request=std::shared_ptr<const Aws::Http::HttpRequest> (use count 2, weak count 0) = {...}, outcome=..., metricsFromCore=...,
    contexts=std::vector of length 0, capacity 0) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/monitoring/MonitoringManager.cpp:60
#1  0x0000555555c3cc29 in Aws::Client::AWSClient::AttemptExhaustively (this=this@entry=0x7ffff671f490, uri=..., request=..., method=method@entry=Aws::Http::HttpMethod::HTTP_GET, signerName=0x7fffbc816f70 "Signat
ureV4",
    signerRegionOverride=0x7fffbc816f30 "us-east-1", signerServiceNameOverride=0x7fffbc816f50 "s3") at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:276
#2  0x0000555555c3ddab in Aws::Client::AWSClient::MakeRequestWithUnparsedResponse (this=this@entry=0x7ffff671f490, uri=..., request=..., method=method@entry=Aws::Http::HttpMethod::HTTP_GET, signerName=<optimized
 out>,
    signerRegionOverride=0x7fffbc816f30 "us-east-1", signerServiceNameOverride=0x7fffbc816f50 "s3") at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:549
#3  0x00005555558adc1a in Aws::S3::S3Client::GetObject (this=0x7ffff671f490, request=...) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1852
#4  0x0000555555870428 in Aws::S3::S3Client::GetObjectAsyncHelper(Aws::S3::Model::GetObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::GetObjectRequest const&, Aws::Utils::Outco
me<Aws::S3::Model::GetObjectResult, Aws::S3::S3Error>, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (this=0x7ffff67
1f490, request=..., handler=..., context=
    std::shared_ptr<const Aws::Client::AsyncCallerContext> (use count 1, weak count 0) = {...}) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1870
#5  0x0000555555cbc29a in std::function<void ()>::operator()() const (this=0x7fffc9a0f278) at /usr/include/c++/7/bits/std_function.h:706
#6  Aws::Utils::Threading::DefaultExecutor::<lambda()>::operator() (__closure=0x7fffc9a0f278) at external/com_github_aws-sdk-cpp/aws-cpp-sdk-core/source/utils/threading/Executor.cpp:18
#7  std::__invoke_impl<void, Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#8  std::__invoke<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#9  std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> > >::_M_invoke<0> (this=0x7fffc9a0f278) at /usr/include/c++/7/thread:234
#10 std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> > >::operator() (this=0x7fffc9a0f278) at /usr/include/c++/7/thread:243
#11 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Aws::Utils::Threading::DefaultExecutor::SubmitToThread(std::function<void()>&&)::<lambda()> > > >::_M_run(void) (this=0x7fffc9a0f270) at /usr/include
/c++/7/thread:186
```

Here also  a `GetObject` was still running in a `Aws::Utils::Threading::DefaultExecutor` at shutdown.

_Line references_ for above traces are in the excerpt below:
```c++
// source/monitoring/MonitoringManager.cpp
void OnRequestFailed(const Aws::String& serviceName, const Aws::String& requestName, const std::shared_ptr<const Aws::Http::HttpRequest>& request,
                const Aws::Client::HttpResponseOutcome& outcome, const CoreMetricsCollection& metricsFromCore, const Aws::Vector<void*>& contexts)
{
    assert(s_monitors); // <== Line 57, SIGABRT
    assert(contexts.size() == s_monitors->size());
    size_t index = 0;
    for (const auto& interface: *s_monitors) // <== Line 60, SIGSEGV
    {
        interface->OnRequestFailed(serviceName, requestName, request, outcome, metricsFromCore, contexts[index++]);
    }
}
```

### Analysis

The `MonitoringManager` has a `CleanupMonitoring` function that _resets_ the `static` global pointer to a `nullptr`.

It is called _early_ during shutdown:
```c++
// source/Aws.cpp
void ShutdownAPI(const SDKOptions& options)
{
    Aws::Monitoring::CleanupMonitoring();  // <== HERE
    Aws::Internal::CleanupEC2MetadataClient();
    Aws::Net::CleanupNetwork();
    Aws::CleanupEnumOverflowContainer();
    Aws::Http::CleanupHttp();
    Aws::Utils::Crypto::CleanupCrypto();
    // ...
}
```

The problem in both cases is that, at the time of shutdown,  `Aws::Utils::Threading::DefaultExecutor` threads were still running to perform `GetObject` requests. Since the `DefaultExecutor` uses detached threads, it is difficult to time the exit of all such threads when the program is shutting down.

### Possible fix

Calling ` Aws::Http::CleanupHttp` before `Aws::Monitoring::CleanupMonitoring` would not help, since the `GetObject{,Async}` calls came from threads that were still running at program shutdown.

A better solution is to _not call_ `CleanupMonitoring` in `Aws::ShutdownAPI` at all, due to the possibility of request in-flight needing to call one of the `MonitoringManager` methods during the time of shutdown. Since the program is shutting down anyway, no memory is lost.

### AWS CPP SDK version used

1.9.x (1.9.170, but problem also on master).

### Compiler and Version used

gcc / clang

### Operating System and version

Linux, ubuntu 18.04

**Comment by jmklix** [comment]
As always thanks for the PR, reviewing and testing
