### ISSUE TITLE
Memory leak caused by S3Client

### ISSUE THREAD

**Issue by nrt9843** [aws/aws-sdk-cpp#2331]
### Describe the bug

Using the AWS S3Client causes a small memory leak, even in simple cases.

### Expected Behavior

S3Client does not cause a memory leak when properly shut down.

### Current Behavior

AddressSanitizer report:

```
==27159==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f7b6240890f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5588ebff77dc in CRYPTO_zalloc crypto/mem.c:197

Indirect leak of 512 byte(s) in 6 object(s) allocated from:
    #0 0x7f7b6240890f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5588ebff77dc in CRYPTO_zalloc crypto/mem.c:197

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f7b6240890f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5588ec039315 in OPENSSL_sk_deep_copy crypto/stack/stack.c:87

Indirect leak of 27 byte(s) in 2 object(s) allocated from:
    #0 0x7f7b6240890f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5588ebff8fc9 in CRYPTO_strdup crypto/o_str.c:27

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f7b6240890f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5588ebff9102 in CRYPTO_strndup crypto/o_str.c:43

Indirect leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f7b62407720 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:85
    #1 0x5588ec002cf8 in ossl_provider_set_operation_bit crypto/provider_core.c:1627

SUMMARY: AddressSanitizer: 723 byte(s) leaked in 12 allocation(s).
```

### Reproduction Steps

Here's a code snippet that reproduces the issue:

```cpp
Aws::SDKOptions o;
Aws::InitAPI(o);
{
    Aws::Client::ClientConfiguration config;
    Aws::S3::S3Client client(config);
}
Aws::ShutdownAPI(o);
```

### AWS CPP SDK version used

1.11.4

### Compiler and Version used

gcc 12.1.0

### Operating System and version

Ubuntu 22.04 (WSL)

**Comment by jmklix** [comment]
I don't see this memory leak on Mac. Going to try to repro on Ubuntu as well

**Comment by ank8690** [comment]
I also face this issue in AWS SDK Version 1.11.8 in Windows 10.

**Comment by kvpendergast** [comment]
I'm using sdk version 2 and experiencing this issue. Here's the code: 

```
import AWS from 'aws-sdk'

export const uploadImage = (key, blob) => {
  AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY,
    secretAccessKey: process.env.AWS_SECRET_KEY,
  });

  const s3 = new AWS.S3({
    signatureVersion: 'v4',
    region: 'us-east-2'
  });

  return s3.upload({
    Bucket: 'my-bucket',
    Key: key,
    Body: blob,
    ContentType: 'image/png'
  }).promise()
}
```

**Comment by jmklix** [comment]
Able to repro this with Ubuntu 22.04
```
==6977== LEAK SUMMARY:
==6977==    definitely lost: 144 bytes in 1 blocks
==6977==    indirectly lost: 579 bytes in 11 blocks
==6977==      possibly lost: 0 bytes in 0 blocks
==6977==    still reachable: 1,507 bytes in 4 blocks
==6977==         suppressed: 0 bytes in 0 blocks
==6977== Reachable blocks (those to which a pointer was found) are not shown.
==6977== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```
Still working on finding the root cause and a fix for this

**Comment by jmklix** [comment]
The fix has been merged. You can get the latest updates from head or wait for tomorrow release. Please let us know if you run into anymore memory leaks
