### ISSUE TITLE
MarketplaceMeteringClient threads cause failed assertions at program exit

### ISSUE THREAD

**Issue by fdrgiit** [aws/aws-sdk-cpp#2387]
### Describe the bug

The issue is same as to what has been described here : https://github.com/aws/aws-sdk-cpp/issues/2274

I am using the [MeterUsage](https://sdk.amazonaws.com/cpp/api/0.14.3/class_aws_1_1_marketplace_metering_1_1_model_1_1_meter_usage_request.html) API, to send Metering records from an AMI. The use of the `MarketplaceMeteringClient` interferes with `Aws::ShutdownAPI` shutdown causes a Fatal error.

### Failed assertion at program exit
We are repeatedly seeing failed assertions of this kind:

```
Successfully submitted metering record
Metering record Id: 6130c768-6b42-4494-90ea-fba41cc830bf
Fatal error condition occurred in /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/allocator.c:209: allocator != ((void *)0)
Exiting Application
No call stack information available
Aborted

#0  0x00007ffff651bca0 in raise () from /lib64/libc.so.6
#1  0x00007ffff7a0cc16 in aws_debug_break () at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/posix/system_info.c:164
#2  0x00007ffff79f8999 in aws_fatal_assert (cond_str=0x7ffff7ac5fae "allocator != ((void *)0)",
    file=0x7ffff7ac5f30 "/root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/allocator.c", line=209)
    at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/assert.c:14
#3  0x00007ffff79f757d in aws_mem_release (allocator=0x0, ptr=0x8c39f0) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/allocator.c:209
#4  0x00007ffff7a08b95 in s_aws_cJSON_free (ptr=0x8c39f0) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/json.c:361
#5  0x00007ffff7a1935d in cJSON_Delete (item=0x88a970) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/external/cJSON.c:265
#6  0x00007ffff7a1932c in cJSON_Delete (item=0x88aa30) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/external/cJSON.c:261
#7  0x00007ffff7a08c44 in aws_json_value_destroy (value=0x88aa30) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/json.c:388
#8  0x00007ffff79ee956 in s_endpoints_ruleset_destroy (data=0x897270) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-sdkutils/source/endpoints_ruleset.c:917
#9  0x00007ffff7a0e0cd in aws_ref_count_release (ref_count=0x897278) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/ref_count.c:29
#10 0x00007ffff79eeae5 in aws_endpoints_ruleset_release (ruleset=0x897270) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-sdkutils/source/endpoints_ruleset.c:955
#11 0x00007ffff79ea22e in s_endpoints_rule_engine_destroy (data=0x888f40) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-sdkutils/source/endpoints_rule_engine.c:873
#12 0x00007ffff7a0e0cd in aws_ref_count_release (ref_count=0x888f48) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/ref_count.c:29
#13 0x00007ffff79ea38f in aws_endpoints_rule_engine_release (rule_engine=0x888f40) at /root/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-sdkutils/source/endpoints_rule_engine.c:908
#14 0x00007ffff77ec883 in Aws::Crt::Endpoints::RuleEngine::~RuleEngine (this=0x8c3bc8, __in_chrg=<optimized out>)
    at /root/aws-sdk-cpp/crt/aws-crt-cpp/source/endpoints/RuleEngine.cpp:156
#15 0x000000000041b344 in Aws::Endpoint::DefaultEndpointProvider<Aws::Client::GenericClientConfiguration<false>, Aws::Endpoint::BuiltInParameters, Aws::Endpoint::ClientContextParameters>::~DefaultEndpointProvider (this=0x8c3bc0, __in_chrg=<optimized out>)
    at /root/aws-sdk-cpp/src/aws-cpp-sdk-core/include/aws/core/endpoint/DefaultEndpointProvider.h:63
#16 0x0000000000419838 in Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider::~MarketplaceMeteringEndpointProvider (this=0x8c3bc0,
    __in_chrg=<optimized out>) at /root/aws-sdk-cpp/generated/src/aws-cpp-sdk-meteringmarketplace/include/aws/meteringmarketplace/MarketplaceMeteringEndpointProvider.h:56
#17 0x0000000000422d71 in __gnu_cxx::new_allocator<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider>::destroy<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider> (this=0x8c3bc0, __p=0x8c3bc0) at /usr/include/c++/7/ext/new_allocator.h:140
#18 0x0000000000422ce9 in std::allocator_traits<std::allocator<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider> >::destroy<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider> (__a=..., __p=0x8c3bc0) at /usr/include/c++/7/bits/alloc_traits.h:487
#19 0x0000000000422ab3 in std::_Sp_counted_ptr_inplace<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider, std::allocator<Aws::MarketplaceMetering::Endpoint::MarketplaceMeteringEndpointProvider>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x8c3bb0) at /usr/include/c++/7/bits/shared_ptr_base.h:535
#20 0x000000000041c494 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x8c3bb0) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#21 0x000000000041a94d in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x9254d8, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/shared_ptr_base.h:684
#22 0x000000000041a38c in std::__shared_ptr<Aws::Endpoint::EndpointProviderBase<Aws::Client::GenericClientConfiguration<false>, Aws::Endpoint::BuiltInParameters, Aws::Endpoint::ClientContextParameters>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x9254d0, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#23 0x000000000041a3a8 in std::shared_ptr<Aws::Endpoint::EndpointProviderBase<Aws::Client::GenericClientConfiguration<false>, Aws::Endpoint::BuiltInParameters, Aws::Endpoint::ClientContextParameters> >::~shared_ptr (this=0x9254d0, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#24 0x00007ffff71b566c in Aws::MarketplaceMetering::MarketplaceMeteringClient::~MarketplaceMeteringClient (this=0x925120, __in_chrg=<optimized out>)
    at /root/aws-sdk-cpp/generated/src/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringClient.cpp:134
#25 0x00007ffff71b56b8 in Aws::MarketplaceMetering::MarketplaceMeteringClient::~MarketplaceMeteringClient (this=0x925120, __in_chrg=<optimized out>)
    at /root/aws-sdk-cpp/generated/src/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringClient.cpp:136
#26 0x000000000041dfba in std::default_delete<Aws::MarketplaceMetering::MarketplaceMeteringClient>::operator() (this=0x7fffffffdf68, __ptr=0x925120)
    at /usr/include/c++/7/bits/unique_ptr.h:78
#27 0x000000000041bf9f in std::unique_ptr<Aws::MarketplaceMetering::MarketplaceMeteringClient, std::default_delete<Aws::MarketplaceMetering::MarketplaceMeteringClient> >::~unique_ptr (this=0x7fffffffdf68, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:268
#28 0x0000000000418814 in call_aws_sdk (productCode=0x422f90 "3xfqnxoyzxndh3fqchoscf7ka", usageDimension=0x422faa "dimension_24_id", timestamp=1678365742000, dryRun=false,
---Type <return> to continue, or q <return> to quit---
    allocatedUsage=0x7fffffffe4e4, tagKeys=0x7fffffffe4d0, tagValues=0x7fffffffe4c0, numAllocatedUsage=2, numTags=2) at latestmeter.cpp:13
#29 0x00000000004182eb in main () at mainlatest.c:33
```

Pseudo code that's generating the above backtrace:

```
#include <aws/core/Aws.h>
#include <aws/meteringmarketplace/MarketplaceMeteringClient.h>
#include <aws/meteringmarketplace/model/MeterUsageRequest.h>
#include <aws/meteringmarketplace/model/UsageAllocation.h>
#include <aws/meteringmarketplace/model/Tag.h>

extern "C" {
    int call_aws_sdk(const char* productCode, const char* usageDimension, int64_t timestamp, bool dryRun, int* allocatedUsage, const char** tagKeys, const char** tagValues, int numAllocatedUsage, int numTags) {
        Aws::SDKOptions options;
        Aws::InitAPI(options);

        Aws::MarketplaceMetering::MarketplaceMeteringClient client;
		.
		.
		.
        Aws::ShutdownAPI(options);
        return outcome.IsSuccess() ? 0 : 1;
    }
}
```

### Expected Behavior

Well the above Fatal error shouldn't happen.

### Current Behavior

Described above.

### Reproduction Steps

Provided pseduo code to repro the issue

### AWS CPP SDK version used

1.11.31

### Compiler and Version used

gcc (7.3.1) and cmake(3.21.2)

### Operating System and version

4.14.304-226.531.amzn2.x86_64

**Comment by jmklix** [comment]
Can you make sure to put your sdk calls in the curly brackets like [this](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/basic-use.html):
```cpp
#include <aws/core/Aws.h>
int main(int argc, char** argv)
{
   Aws::SDKOptions options;
   Aws::InitAPI(options);
   {
      // make your SDK calls here.
   }
   Aws::ShutdownAPI(options);
   return 0;
}
```

**Comment by fdrgiit** [comment]
@jmklix Thanks, that fixed the issue. Missed a silly thing 👍
