### ISSUE TITLE
Crash in Aws::SQS::SQSClient::SendMessage 

### ISSUE THREAD

**Issue by patilarpith** [aws/aws-sdk-cpp#253]
This only seem to be only occurring when the executable is built on a different server. In my setup the executable is build on a central build server and rsynced to all the worker instances. 

**Build server details:**
Ubuntu 14.04.4 LTS x86_64
Aws Lib: Release 0.13.11 

**Worker server details:**
Ubuntu 14.04.4 LTS x86_64
Aws Lib: Release 0.13.11 

**Build parameters:**

```
cmake -DBUILD_ONLY="s3;sqs" -DCMAKE_BUILD_TYPE=Release -DCUSTOM_MEMORY_MANAGEMENT=0 ..
```

**Stack trace:**

```
(gdb) bt
#0  0x000000000041ec95 in __gnu_cxx::new_allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >::destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > (this=0x1a16fa0, 
    __p=0x7f6a05ad0210 <vtable for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >+24>)
    at /usr/include/c++/4.8/ext/new_allocator.h:124
#1  0x000000000041ec32 in std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::_S_destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > (__a=..., 
    __p=0x7f6a05ad0210 <vtable for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >+24>)
    at /usr/include/c++/4.8/bits/alloc_traits.h:281
#2  0x000000000041eb7e in std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > (__a=..., 
    __p=0x7f6a05ad0210 <vtable for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >+24>)
    at /usr/include/c++/4.8/bits/alloc_traits.h:405
#3  0x000000000041ea83 in std::_Sp_counted_ptr_inplace<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x1a16f90)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:407
#4  0x00007f6a06ba5aa7 in Aws::Http::Standard::StandardHttpRequest::~StandardHttpRequest() () from /usr/local/lib/libaws-cpp-sdk-core.so
#5  0x00007f6a06b980e5 in Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /usr/local/lib/libaws-cpp-sdk-core.so
#6  0x00007f6a06b981e0 in Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /usr/local/lib/libaws-cpp-sdk-core.so
#7  0x00007f6a06b9b721 in Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const () from /usr/local/lib/libaws-cpp-sdk-core.so
#8  0x00007f6a068e3eb8 in Aws::SQS::SQSClient::SendMessage(Aws::SQS::Model::SendMessageRequest const&) const ()
   from /usr/local/lib/libaws-cpp-sdk-sqs.so
#9  0x000000000040af09 in sqs_put_message (queue_url=..., message_body=...) at ./helpers/aws_helper.cpp:587
#10 0x000000000041f087 in SQSImplementationTests () at ./helpers/test/aws_helper_test.cpp:66
#11 0x00000000004212b4 in main (argc=1, argv=0x7ffedf14fdc8) at ./helpers/test/aws_helper_test.cpp:221
```

**ld dependencies:**

```
    linux-vdso.so.1 =>  (0x00007ffc716da000)
    libconfig++.so.9 => /usr/lib/x86_64-linux-gnu/libconfig++.so.9 (0x00007fe8c4957000)
    libPocoFoundation.so.9 => /usr/lib/libPocoFoundation.so.9 (0x00007fe8c460b000)
    libaws-cpp-sdk-core.so => /usr/local/lib/libaws-cpp-sdk-core.so (0x00007fe8c433a000)
    libaws-cpp-sdk-sqs.so => /usr/local/lib/libaws-cpp-sdk-sqs.so (0x00007fe8c405a000)
    libaws-cpp-sdk-s3.so => /usr/local/lib/libaws-cpp-sdk-s3.so (0x00007fe8c3b7e000)
    libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007fe8c3917000)
    libjsoncpp.so.0 => /usr/lib/x86_64-linux-gnu/libjsoncpp.so.0 (0x00007fe8c36f7000)
    libboost_filesystem.so.1.56.0 => /opt/boost/lib/libboost_filesystem.so.1.56.0
    libboost_system.so.1.56.0 => /opt/boost/lib/libboost_system.so.1.56.0
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe8c33f3000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe8c31dd000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe8c2e18000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe8c2bfa000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fe8c29bc000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe8c27a3000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe8c259f000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe8c2397000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe8c2091000)
    libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe8c1cb5000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fe8c4b6d000)
    libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007fe8c1a82000)
    librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007fe8c1868000)
    libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe8c1609000)
    libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fe8c13c2000)
    liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fe8c11b3000)
    libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fe8c0f62000)
    libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007fe8c0ca4000)
    libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007fe8c0a24000)
    libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fe8c0759000)
    libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fe8c052a000)
    libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fe8c0326000)
    libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fe8c011b000)
    libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fe8bff00000)
    libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fe8bfce5000)
    libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fe8bfaa7000)
    libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fe8bf893000)
    libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fe8bf651000)
    libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fe8bf44c000)
    libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fe8bf248000)
    libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fe8bf03f000)
    libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fe8bedb7000)
    libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fe8beb16000)
    libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fe8be8e3000)
    libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007fe8be6ce000)
    libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fe8be4c6000)
    libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007fe8be29d000)
    libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fe8be08f000)
    libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fe8bde46000)
    libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fe8bdb8d000)
    libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fe8bd954000)
```

Has anyone noticed similar issue? It only seem to be affecting SQS operations. S3 seem to be working just fine

**Comment by patilarpith** [comment]
@JonathanHenson Please take a look at this when you get a chance

**Comment by DraconPern** [comment]
Most likely different versions of shared libs between build server and worker instance.

**Comment by patilarpith** [comment]
@DraconPern Both the servers are running 0.13.11 release

**Comment by JonathanHenson** [comment]
Sorry for the delay. We run this code on each platform before release.  Could you possibly send me valgrind output. Also, can you verify your stack size?

**Comment by patilarpith** [comment]
Stack is set to default which is 8mb

Here is the valgrind memcheck log

```
valgrind --tool=memcheck ./aws_unit_test 
==9706== Memcheck, a memory error detector
==9706== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==9706== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==9706== Command: ./aws_unit_test
==9706== 
@SQS_Put_Message[:Message]:=	SQSImplementationTest-0
==9706== Jump to the invalid address stated on the next line
==9706==    at 0x10EC8348FB894853: ???
==9706==    by 0x41EC31: std::enable_if<std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::__destroy_helper<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >::value, void>::type std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::_S_destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >(std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >&, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) (alloc_traits.h:281)
==9706==    by 0x41EB7D: void std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >(std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >&, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) (alloc_traits.h:405)
==9706==    by 0x41EA82: std::_Sp_counted_ptr_inplace<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:407)
==9706==    by 0x5408EE6: Aws::Http::Standard::StandardHttpRequest::~StandardHttpRequest() (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FB574: Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FB66F: Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FEBB0: Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x56F2347: Aws::SQS::SQSClient::SendMessage(Aws::SQS::Model::SendMessageRequest const&) const (in /usr/local/lib/libaws-cpp-sdk-sqs.so)
==9706==    by 0x40AF08: sqs_put_message(std::string, std::string) (aws_helper.cpp:587)
==9706==    by 0x41F086: SQSImplementationTests() (aws_helper_test.cpp:66)
==9706==    by 0x4212B3: main (aws_helper_test.cpp:221)
==9706==  Address 0x10ec8348fb894853 is not stack'd, malloc'd or (recently) free'd
==9706== 
==9706== 
==9706== Process terminating with default action of signal 11 (SIGSEGV)
==9706==  Bad permissions for mapped region at address 0x10EC8348FB894853
==9706==    at 0x10EC8348FB894853: ???
==9706==    by 0x41EC31: std::enable_if<std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::__destroy_helper<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >::value, void>::type std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::_S_destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >(std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >&, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) (alloc_traits.h:281)
==9706==    by 0x41EB7D: void std::allocator_traits<std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > > >::destroy<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >(std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >&, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*) (alloc_traits.h:405)
==9706==    by 0x41EA82: std::_Sp_counted_ptr_inplace<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:407)
==9706==    by 0x5408EE6: Aws::Http::Standard::StandardHttpRequest::~StandardHttpRequest() (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FB574: Aws::Client::AWSClient::AttemptOneRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FB66F: Aws::Client::AWSClient::AttemptExhaustively(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x53FEBB0: Aws::Client::AWSXMLClient::MakeRequest(std::string const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod) const (in /usr/local/lib/libaws-cpp-sdk-core.so)
==9706==    by 0x56F2347: Aws::SQS::SQSClient::SendMessage(Aws::SQS::Model::SendMessageRequest const&) const (in /usr/local/lib/libaws-cpp-sdk-sqs.so)
==9706==    by 0x40AF08: sqs_put_message(std::string, std::string) (aws_helper.cpp:587)
==9706==    by 0x41F086: SQSImplementationTests() (aws_helper_test.cpp:66)
==9706==    by 0x4212B3: main (aws_helper_test.cpp:221)
==9706== 
==9706== HEAP SUMMARY:
==9706==     in use at exit: 479,454 bytes in 6,026 blocks
==9706==   total heap usage: 8,168 allocs, 2,142 frees, 860,328 bytes allocated
==9706== 
==9706== LEAK SUMMARY:
==9706==    definitely lost: 0 bytes in 0 blocks
==9706==    indirectly lost: 0 bytes in 0 blocks
==9706==      possibly lost: 5,658 bytes in 100 blocks
==9706==    still reachable: 473,796 bytes in 5,926 blocks
==9706==         suppressed: 0 bytes in 0 blocks
==9706== Rerun with --leak-check=full to see details of leaked memory
==9706== 
==9706== For counts of detected and suppressed errors, rerun with: -v
==9706== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by patilarpith** [comment]
@JonathanHenson reminder

**Comment by JonathanHenson** [comment]
Sorry for the delay. Are you able to successfully make S3 requests? Also, have you tried updating to latest release?

**Comment by marcomagdy** [comment]
Not enough information to keep this issue open.
Please comment if you're still experiencing this problem with the SDK.
