### ISSUE TITLE
Segmentation fault on TransferManager::TriggerTransferStatusUpdatedCallback

### ISSUE THREAD

**Issue by surreylabs** [aws/aws-sdk-cpp#326]
I use the following code snippet to transfer a file to S3:

```
  Aws::Transfer::TransferManagerConfiguration transferConfig;
  transferConfig.s3Client = s3Client;

  Aws::Transfer::TransferManager transferManager(transferConfig);
  auto transferHandle = transferManager.UploadFile(requestStream, m_bucket, uuid, "application/octet-stream", Aws::Map<Aws::String, Aws::String>());
  transferHandle->WaitUntilFinished();
```

However, the application randomly crashes when `TransferManager` tries to call `TriggerTransferStatusUpdatedCallback`. I don't even set `TransferManagerConfiguration.transferStatusUpdatedCallback`, so why the SDK would crash on this line? Because according to `TransferManager.cpp`, if the callback function is not set, it should not be called in the `TriggerTransferStatusUpdatedCallback` function. Here is the back trace from gdb:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffaefdd700 (LWP 18741)]
0x00007ffff65ce189 in std::function<void (Aws::Transfer::TransferManager const*, Aws::Transfer::TransferHandle const&)>::operator()(Aws::Transfer::TransferManager const*, Aws::Transfer::TransferHandle const&) const (
    this=0x7fffaf7db338, __args#0=0x7fffaf7daca0, __args#1=...) at /usr/include/c++/4.9/functional:2440
2440          return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
(gdb) bt
#0  0x00007ffff65ce189 in std::function<void (Aws::Transfer::TransferManager const*, Aws::Transfer::TransferHandle const&)>::operator()(Aws::Transfer::TransferManager const*, Aws::Transfer::TransferHandle const&) const (
    this=0x7fffaf7db338, __args#0=0x7fffaf7daca0, __args#1=...) at /usr/include/c++/4.9/functional:2440
#1  0x00007ffff65c5934 in Aws::Transfer::TransferManager::TriggerTransferStatusUpdatedCallback (this=0x7fffaf7daca0, handle=...) at /home/tomghuang/Projects/aws-sdk-cpp/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp:538
#2  0x00007ffff65c4d1a in Aws::Transfer::TransferManager::HandlePutObjectResponse (this=0x7fffaf7daca0, request=..., outcome=..., context=std::shared_ptr (count 2, weak 0) 0x7fffd00161d0)
    at /home/tomghuang/Projects/aws-sdk-cpp/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp:417
#3  0x00007ffff65c3c9c in Aws::Transfer::TransferManager::<lambda(const Aws::S3::S3Client*, const Aws::S3::Model::PutObjectRequest&, const PutObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)>::operator()(const Aws::S3::S3Client *, const Aws::S3::Model::PutObjectRequest &, const Aws::S3::Model::PutObjectOutcome &, const std::shared_ptr<Aws::Client::AsyncCallerContext const> &) const (__closure=0x7fffd0018d60, client=0x7fffc01c3e20,
    request=..., outcome=..., context=std::shared_ptr (count 2, weak 0) 0x7fffd00161d0) at /home/tomghuang/Projects/aws-sdk-cpp/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp:316
#4  0x00007ffff65c8003 in std::_Function_handler<void(const Aws::S3::S3Client*, const Aws::S3::Model::PutObjectRequest&, const Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> >&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&), Aws::Transfer::TransferManager::DoSinglePartUpload(const std::shared_ptr<std::basic_iostream<char> >&, const std::shared_ptr<Aws::Transfer::TransferHandle>&)::<lambda(const Aws::S3::S3Client*, const Aws::S3::Model::PutObjectRequest&, const PutObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> >::_M_invoke(const std::_Any_data &, const Aws::S3::S3Client *, const Aws::S3::Model::PutObjectRequest &, const Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > &, const std::shared_ptr<Aws::Client::AsyncCallerContext const> &) (__functor=..., __args#0=0x7fffc01c3e20, __args#1=...,
    __args#2=..., __args#3=std::shared_ptr (count 2, weak 0) 0x7fffd00161d0) at /usr/include/c++/4.9/functional:2039
#5  0x00007ffff65394d2 in std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::PutObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)>::operator()(Aws::S3::S3Client const*, Aws::S3::Model::PutObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (this=0x7fffd0018cb8, __args#0=0x7fffc01c3e20, __args#1=..., __args#2=..., __args#3=std::shared_ptr (count 2, weak 0) 0x7fffd00161d0) at /usr/include/c++/4.9/functional:2440
#6  0x00007ffff64a0562 in Aws::S3::S3Client::PutObjectAsyncHelper(Aws::S3::Model::PutObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::PutObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::PutObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const (this=0x7fffc01c3e20,
    request=..., handler=..., context=std::shared_ptr (count 2, weak 0) 0x7fffd00161d0) at /home/tomghuang/Projects/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1939
#7  0x00007ffff64a03ab in Aws::S3::S3Client::<lambda()>::operator()(void) const (__closure=0x7fffd0018a70) at /home/tomghuang/Projects/aws-sdk-cpp/aws-cpp-sdk-s3/source/S3Client.cpp:1934
#8  0x00007ffff64d2c58 in std::_Bind<Aws::S3::S3Client::PutObjectAsync(const Aws::S3::Model::PutObjectRequest&, const PutObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()>::__call<void>(<unknown type in /home/ubuntu/temp/libOrthancAwsS3Storage.so, CU 0xa28a2, DIE 0x29fe99>, std::_Index_tuple<>) (this=0x7fffd0018a70,
    __args=<unknown type in /home/ubuntu/temp/libOrthancAwsS3Storage.so, CU 0xa28a2, DIE 0x29fe99>) at /usr/include/c++/4.9/functional:1264
#9  0x00007ffff64ce56e in std::_Bind<Aws::S3::S3Client::PutObjectAsync(const Aws::S3::Model::PutObjectRequest&, const PutObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()>::operator()<, void>(void) (this=0x7fffd0018a70) at /usr/include/c++/4.9/functional:1323
#10 0x00007ffff64c0aa9 in std::_Function_handler<void(), std::_Bind<Aws::S3::S3Client::PutObjectAsync(const Aws::S3::Model::PutObjectRequest&, const PutObjectResponseReceivedHandler&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&) const::<lambda()>()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/4.9/functional:2039
#11 0x00007ffff65fa2da in std::function<void ()>::operator()() const (this=0x7fffd0018da8) at /usr/include/c++/4.9/functional:2440
#12 0x00007ffff65fa2a6 in std::_Bind_simple<std::function<void ()> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x7fffd0018da8) at /usr/include/c++/4.9/functional:1700
#13 0x00007ffff65fa1f1 in std::_Bind_simple<std::function<void ()> ()>::operator()() (this=0x7fffd0018da8) at /usr/include/c++/4.9/functional:1688
#14 0x00007ffff65fa16e in std::thread::_Impl<std::_Bind_simple<std::function<void ()> ()> >::_M_run() (this=0x7fffd0018d90) at /usr/include/c++/4.9/thread:115
#15 0x00007ffff7329c30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff7bc4184 in start_thread (arg=0x7fffaefdd700) at pthread_create.c:312
#17 0x00007ffff6ab137d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

**Comment by bretambrose** [comment]
Can you give us your platform details (os/compiler/stdlib versions) as well as anything unusual about your test case?  For example, we know there are transfer issues with filenames that contain unusual unicode characters.

You say randomly so I'm guessing it's not 100% repeatable.  Any guesses on the frequency?

**Comment by surreylabs** [comment]
Here are some details about my system:

- Ubuntu 14.10
- gcc 4.8.5 and gcc 4.9.4 (I've tried both versions, but the result is the same.)
- libc 2.19

When I ran my application on my laptop (8 GB RAM), it didn't crash. However, when I ran it on t2.micro instance (1 GB RAM), it crashed all the time. I guess it might related to low memory. However, I couldn't find the root cause from the stack trace.
