### ISSUE TITLE
Segmentation Fault When Downloading File Byte Ranges

### ISSUE THREAD

**Issue by hnaik** [aws/aws-sdk-cpp#649]
We are trying to download large binary files in chunks with specified byte-ranges. These chunks are then used by the application for further processing. We are noticing that after processing a few hundred such segments, the process randomly segfaults. Here is the stack trace from the core file:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2041ee5b35 in Aws::Transfer::TransferManager::TriggerTransferStatusUpdatedCallback(Aws::Transfer::TransferHandle const&) const () from /path/builddir/EXT/Install/lib/libaws-cpp-sdk-transfer.so
[Current thread is 1 (Thread 0x7f202f9a9700 (LWP 14515))]
(gdb) bt
#0  0x00007f2041ee5b35 in Aws::Transfer::TransferManager::TriggerTransferStatusUpdatedCallback(Aws::Transfer::TransferHandle const&) const () from /path/builddir/EXT/Install/lib/libaws-cpp-sdk-transfer.so
#1  0x00007f2041ee988c in Aws::Transfer::TransferManager::HandleGetObjectResponse(Aws::S3::S3Client const*, Aws::S3::Model::GetObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::GetObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) () from /path/builddir/EXT/Install/lib/libaws-cpp-sdk-transfer.so
#2  0x00007f20416a5575 in Aws::S3::S3Client::GetObjectAsyncHelper(Aws::S3::Model::GetObjectRequest const&, std::function<void (Aws::S3::S3Client const*, Aws::S3::Model::GetObjectRequest const&, Aws::Utils::Outcome<Aws::S3::Model::GetObjectResult, Aws::Client::AWSError<Aws::S3::S3Errors> > const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&)> const&, std::shared_ptr<Aws::Client::AsyncCallerContext const> const&) const () from /path/builddir/EXT/Install/lib/libaws-cpp-sdk-s3.so
#3  0x00007f2042bd2bff in std::execute_native_thread_routine (__p=0x7f2028132860) at /path/bin/gcc-6.2.0/libstdc++-v3/src/c++11/thread.cc:83
#4  0x00007f2046baf6ba in start_thread (arg=0x7f202f9a9700) at pthread_create.c:333
#5  0x00007f20426413dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Left alone, it usually takes a few hours to crash but I am able to make this happen sooner by starting a build in another terminal session (with say 'make -j8' and cause this unrelated process use a lot of machine memory).

**Comment by singku** [comment]
Thank you for reporting this. This might be the same cause currently discussed in another issue, #647

**Comment by singku** [comment]
Already fixed
